// Types for the vendored Signalsmith Stretch Emscripten factory
// (signalsmithCore.js — regenerated by scripts/vendor-signalsmith.mjs).
// Boolean-like WASM parameters are numbers (0 | 1) at the ABI boundary.

export interface SignalsmithWasmModule {
  /** One-time engine init; call once right after the factory resolves. */
  _main(): void;
  _presetDefault(channels: number, sampleRate: number): void;
  _presetCheaper(channels: number, sampleRate: number): void;
  /** Direct configuration. splitComputation=1 spreads FFT work across blocks (live use). */
  _configure(
    channels: number,
    blockSamples: number,
    intervalSamples: number,
    splitComputation: number,
  ): void;
  _reset(): void;
  /** Latencies in samples; constant after _configure. */
  _inputLatency(): number;
  _outputLatency(): number;
  /**
   * Allocates interleaved-by-channel I/O buffers of `bufferLength` samples each
   * and returns the base pointer. Input channel c starts at
   * base + bufferLength*4*c; output channel c at base + bufferLength*4*(channels + c).
   */
  _setBuffers(channels: number, bufferLength: number): number;
  /** tonalityLimit is a fraction of the sample rate (e.g. 8000/sampleRate). */
  _setTransposeSemitones(semitones: number, tonalityLimit: number): void;
  /** compensatePitch=1 preserves the original spectral envelope under transposition. */
  _setFormantSemitones(semitones: number, compensatePitch: number): void;
  /** Fundamental for formant analysis as a fraction of sample rate; 0 = auto-detect. */
  _setFormantBase(normalizedFreq: number): void;
  /** Consumes inputSamples from the input buffers, writes outputSamples to the output buffers. */
  _process(inputSamples: number, outputSamples: number): void;
  _seek(samples: number, rate: number): void;
  /** WASM heap view; re-read `.buffer` after every call in case memory grew. */
  HEAP8: Int8Array;
  exports?: { memory: WebAssembly.Memory };
}

declare function SignalsmithStretch(moduleArg?: object): Promise<SignalsmithWasmModule>;
export default SignalsmithStretch;
